# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0cdad0e9c3e9a4d94134d1bcf318477ac1d9983f79c98b60cf5cb0a0e41ae0380b28a62733e10fe3f083d8bf03c2aa02fd72ba846d0d5a9a9e01d0a3a17b0bf8

test:
  secret_key_base: 9f941171876222e440a9721fbe31d5e7f7a469d4db66e7c5aa4c23f3ddb04845d40c243943848c15e695a0afaceecd0f99a6adc2d6d0e3e95bab1d7754d5343d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
